### ISSUE TITLE
ECS 8.0 Meta Issue

### ISSUE THREAD

**Issue by r00tu53r** [elastic/integrations#2363]
This issue acts as a meta issue that tracks changes being made for all integration packages that require changes for [ECS 8.0](https://github.com/elastic/ecs/blob/7d997dd30c657659f58c3be1867d7b37a92ce2cb/CHANGELOG.next.md#800-hard-feature-freeze)

### Security External Integration Packages

| Package      | PR link       |   Notes             |
| ----------- | ----------- | ---------------- |
| 1password | #2368  |  |
| akamai | #2369  |  |
| atlassian_bitbucket | #2376 |  |
| atlassian_confluence | #2378   |  |
| atlassian_jira | #2379 |  |
| auditd | #2380 |  |
| barracuda | #2381 |  |
| bluecoat | #2382  |  |
| carbonblack_edr | #2385 |  |
| cef | #2386 |  |
| checkpoint | #2387 |  |
| cisco | not available for 8.0 | PR #2388 will be closed |
| cisco_asa | #2389 |  |
| cisco_duo | #2390 |  |
| cisco_ftd | #2391 |  |
| cisco_ios | #2392 |  |
| cisco_meraki | #2393  |  |
| cisco_nexus | #2394 |  |
| cisco_secure_endpoint | #2395 |  |
| cisco_umbrella | #2396 |  |
| cloudflare | #2397 |  |
| crowdstrike | #2398 |  |
| cyberark | not available for 8.0 | PR #2399 will be closed |
| cyberarkpas | #2400 |  |
| cylance | #2402 |  |
| f5 | #2403 |  |
| fireeye | #2404 |  |
| fortinet | #2405 |  |
| gcp | #2406 |  |
| github | #2407 |  |
| google_workspace | #2408 |  |
| hashicorp_vault | #2409 |  |
| httpjson | not applicable |  |
| imperva | #2410 |  |
| infoblox | #2411 |  |
| iptables | #2414 |  |
| juniper | #2415 |  |
| juniper_junos | #2416 |  |
| juniper_netscreen | #2417 |  |
| juniper_srx |  #2418 |  |
| keycloak | #2419 |  |
| mattermost | #2420 |  |
| microsoft | not applicable for 8.0 | PR #2421 will be closed |
| microsoft_defender_endpoint | #2422  |  |
| microsoft_dhcp | #2423 |  |
| microsoft_sqlserver | #2493 |  |
| netflow | #2424 |  |
| netscout | #2425 |  |
| network_traffic | #2426 |  |
| o365 | #2427 |  |
| okta | #2428 |  |
| osquery | #2429 |  |
| panw | #2430 |  |
| panw_cortex_xdr | #2431 |  |
| pfsense | #2432 |  |
| proofpoint | #2433 |  |
| pulse_connect_secure | #2434 |  |
| qnap_nas | #2435 |  |
| radware | #2436 |  |
| santa | #2437 |  |
| snort | #2438 |  |
| snyk | #2439 |  |
| sonicwall | #2440 |  |
| sophos | #2441 |  |
| squid | #2442 |  |
| suricata | #2443 |  |
| tcp | not applicable |  |
| tenable_sc | #2444 |  |
| ti_abusech | #2445 |  |
| ti_anomali | #2446 |  |
| ti_cybersixgill | #2447 |  |
| ti_misp | #2448 |  |
| ti_otx | #2449 |  |
| ti_threatq | #2450 |  |
| tomcat | #2451 |  |
| udp | not applicable |  |
| winlog | not applicable |  |
| zeek | #2452 |  |
| zerofox | #2453 |  |
| zoom | #2454 |  |
| zscaler | not applicable for 8.0 | PR #2455 will be closed |

### Integration Packages

| Package      | PR link       |   Notes             |
| ----------- | ----------- | ---------------- |
| activemq | #2456 |  |
| apache | #2460 |  |
| aws | #2478 |  |
| azure | #2479 |  |
| azure_application_insights | #2480 | No pipelines and tests to run and cannot re-generate sample event |
| azure_billing | #2481 | No pipelines and tests to run and cannot re-generate sample event  |
| azure_metrics | #2482 |  |
| cassandra | #2483 |  |
| cockroachdb | #2484 |  |
| docker | not applicable |  |
| elasticsearch | not applicable |  |
| etcd | #2486 |  |
| haproxy | #2488 |  |
| iis | #2489 |  |
| journald | not applicable |  |
| kafka | #2490 |  |
| kibana | not applicable |  |
| kubernetes | #2491 |  |
| linux | #2492 |  |
| log | not applicable |  |
| logstash | not applicable |  |
| modsecurity | not applicable |  |
| mongodb | #2494 |  |
| mysql | #2496 |  |
| nats | #2504 |  |
| nginx | #2505 |  |
| nginx_ingress_controller | #2506 |  |
| postgresql | #2507 |  |
| prometheus | #2508 |  |
| rabbitmq | #2509 |  |
| redis | #2510 |  |
| stan | #2511  |  |
| system | #2512 |  |
| traefik | #2513 |  |
| vsphere | #2514 |  |
| windows | #2515 |  |
| zookeeper | #2516 |  |

**Comment by andrewkroh** [comment]
I'm debating about what `kibana.version` constraints should be associated with these changes. Most packages currently use `^7.16.0 || ^8.0.0`. ECS 8.0 contains some [breaking changes](https://github.com/elastic/ecs/blob/7d997dd30c657659f58c3be1867d7b37a92ce2cb/CHANGELOG.next.md#breaking-changes-2). elastic/beats was updated for 8.0 to implement ECS 8.0. So this made some breaking changes to data from Beats.

- Do we want `ecs.version: 8.0.0` data available in 7.16? Are there other parts Elastic Stack 7.16 that will fail if they get ECS 8.0.0 data? Like will the Logs UI fail if when `log.original` is removed?

- If we only want to introduce ECS 8.0 to stack version >=8.0 then what happens to integration users that are on 7.16? We would lose the ability to provide LTS to 7.16 users. We should not take an approach where we cannot support 7.16 users so this seems like a no-go.

Unless elastic/integrations creates a 7.16 branch, the integrations need to continue supporting 7.16. So I think we should keep the kibana.constraint at `^7.16.0 || ^8.0.0` and adapt the integrations to implement `ecs.version: 8.0.0` with data coming from agent 7.16 or agent 8.0. This does mean that 7.16 users will see ecs.version: 8.0.0 data.

**Comment by mtojek** [comment]
> I'm debating about what kibana.version constraints should be associated with these changes. Most packages currently use ^7.16.0 || ^8.0.0. ECS 8.0 contains some breaking changes. elastic/beats was updated for 8.0 to implement ECS 8.0. So this made some breaking changes to data from Beats.

Based on what you stated here and thinking about the dependency nightmare in the future, I would suggest cutting and forgetting about the 7.16 compatibility. We would focus on 8.0.0 with a clear mind and no legacy constraints. I understand it's impossible, so...

>  the integrations need to continue supporting 7.16. So I think we should keep the kibana.constraint at ^7.16.0 || ^8.0.0 and adapt the integrations to implement ecs.version: 8.0.0 with data coming from agent 7.16 or agent 8.0.

This, as we (Ecosystem) discussed a lot `Unless elastic/integrations create a 7.16 branch,` and wouldn't like to create and maintain that branch unless it's REALLY necessary. It will generate additional operational load and we'd like to keep it simple.

WDYT @ruflin? @masci?

**Comment by ruflin** [comment]
My personal take is that we should focus on the 8.0 release as ECS 8.0 is targeted on 8.0. It seems the breaking changes in ECS do not have to necessarily impact each integration. For example if log.original is removed, an integration could still use it or put an alias in assuming no data flows in through this field. Otherwise ingest pipelines have to be used.

One of the goals of 7.16 is to make migration to 8 as easy as possible. Many enhancements in integrations likely also need a new version of the stack to work.

I would like for us to think through all the migration cases / problems before making a call on using ECS 8.0 with the breaking changes. We need to make sure to not get our users into a state where they are stuck because of conflicts.

**Comment by jsoriano** [comment]
I was looking at one of the open PRs (https://github.com/elastic/integrations/pull/2494), and I see that there is no change to the fields included in the package, only the ECS version changes. Do we need these changes? Cannot these modules continue using the ECS version they are using now?

**Comment by r00tu53r** [comment]
> I was looking at one of the open PRs (#2494), and I see that there is no change to the fields included in the package, only the ECS version changes. Do we need these changes? Cannot these modules continue using the ECS version they are using now?

I was in the impression that since this is a major version change and has breaking changes compared to ECS 1.12 it might be easier to update all packages to the next major version (8.0) that way any future modifications to the package work in 8.0. 

Also in some cases there were documentation updates to fields that are not breaking changes. I have merged a few PRs that are in question, I will wait for a decision on those. If required I can revert them.

**Comment by r00tu53r** [comment]
@jsoriano Regarding the [comment](https://github.com/elastic/integrations/pull/2496#issuecomment-1019977420) -

For the packages that had `kibana.version` set to `7.x.y || 8.0`, the ECS versions were updated considering that those packages would be available in 8.0. Otherwise the packages would still use ECS 1.12 schema and be made available in 8.0.

**Comment by r00tu53r** [comment]
> I was looking at one of the open PRs (#2494), and I see that there is no change to the fields included in the package, only the ECS version changes. Do we need these changes? Cannot these modules continue using the ECS version they are using now?

All those packages that were marked with `kibana.version` with `8.0` were updated for ECS 8.0. Some had field changes while in some cases there were documentation updates to fields that are not breaking changes. 

I have merged a few PRs that are in question, I will wait for a decision on those. If required I can revert them.

**Comment by r00tu53r** [comment]
@andrewkroh The packages below has breaking changes for ECS 8.0. They were marked for `7.x || 8.0` release on the `main` branch. I believe they must only be set for `8.0` with the current ECS update?

```
auditd: version: 1.3.1, kibana.version: ^7.14.0 || ^8.0.0, release: ga
barracuda: version: 0.8.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
bluecoat: version: 0.7.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
cisco_asa: version: 2.0.0, kibana.version: ^7.16.0 || ^8.0.0, release: ga
cisco_ftd: version: 2.0.0, kibana.version: ^7.16.0 || ^8.0.0, release: ga
cisco_meraki: version: 0.4.0, kibana.version: ^7.16.0 || ^8.0.0, release: experimental
cisco_nexus: version: 0.4.0, kibana.version: ^7.16.0 || ^8.0.0, release: experimental
cisco_secure_endpoint: version: 1.0.0, kibana.version: ^7.16.0 || ^8.0.0, release: ga
cylance: version: 0.7.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
f5: version: 0.8.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
fortinet: version: 1.4.0, kibana.version: ^7.14.1 || ^8.0.0, release: ga
imperva: version: 0.7.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
infoblox: version: 0.7.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
iptables: version: 0.7.0, kibana.version: ^7.16.0 || ^8.0.0, release: beta
linux: version: 0.6.2, kibana.version: ^7.14.0 || ^8.0.0, release: beta
microsoft: version: 1.2.0, kibana.version: ^7.14.1, release: experimental
microsoft_defender_endpoint: version: 2.0.0, kibana.version: ^7.14.1 || ^8.0.0, release: ga
netflow: version: 1.3.0, kibana.version: ^7.14.0 || ^8.0.0, release: ga
netscout: version: 0.7.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
osquery: version: 2.0.0, kibana.version: ^7.14.0 || ^8.0.0, release: ga
osquery_manager: version: 1.0.0, kibana.version: ^7.16.0 || ^8.0.0, release: ga
panw: version: 2.0.0, kibana.version: ^7.14.0 || ^8.0.0, release: ga
proofpoint: version: 0.6.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
radware: version: 0.6.0, kibana.version: ^7.14.0 || ^8.0.0, release: experimental
santa: version: 1.1.0, kibana.version: ^7.16.0 || ^8.0.0, release: ga
sonicwall: version: 0.7.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
sophos: version: 1.2.0, kibana.version: ^7.14.1 || ^8.0.0, release: ga
squid: version: 0.7.0, kibana.version: ^7.14.1 || ^8.0.0, release: experimental
system: version: 1.10.0, kibana.version: ^7.16.0 || ^8.0.0, release: ga
tomcat: version: 1.3.0, kibana.version: ^7.14.1 || ^8.0.0, release: ga
```

These have breaking changes too but their version is only set for `8.0`. Which should be okay - 

```
juniper: version: 1.1.0, kibana.version: ^8.0.0, release: ga
juniper_junos: version: 0.1.0, kibana.version: ^8.0.0, release: experimental
juniper_netscreen: version: 0.1.0, kibana.version: ^8.0.0, release: experimental
juniper_srx: version: 1.1.0, kibana.version: ^8.0.0, release: ga
```

**Comment by jsoriano** [comment]
> For the packages that had `kibana.version` set to `7.x.y || 8.0` (on `main` branch), the ECS versions were updated considering that those packages would be available in 8.0. Otherwise the packages would still use ECS 1.12 schema and be made available in 8.0.

@r00tu53r what I don't fully understand is if it would be a problem to continue using ECS 1.12 in packages that don't have any field that is different between both versions, as the ones where I commented. If it is not a problem, then we wouldn't need to apply the change in all these packages.

My concern is not only about this change specifically, but about continuing to rely on this kind of bulk changes. We plan to open the packages ecosystem to more teams, and potentially to the community, we need to understand well what kind of changes really need to be applied to all packages, because communication on this will be more complicated in the future, and not all teams are going to have the same bandwidth to follow these requirements.

**Comment by ruflin** [comment]
The part I'm still missing, what is the migration story if there is a breaking change? See https://github.com/elastic/integrations/issues/2363#issuecomment-999625964 Have we tested how users get from 7.last to 8.0? What happens if they have old and new agents ingesting data?

**Comment by r00tu53r** [comment]
@jsoriano Yes you're right for packages that don't have any field changes I don't see any issue. If we didn't update the ECS version then we would have all those packages using ECS 1.12 fields in 8.0. It shouldn't matter for packages that don't have breaking changes. As you see above there a few packages with breaking changes. The question I have is - is it okay to have packages using ECS 1.12 spec be used in 8.0 stack. We will have to track if someone made a change to a field set and used a ECS 1.12 field that breaks in 8.0 on each commit to those packages.

**Comment by andrewkroh** [comment]
## Transitioning from Agent 7.x to 8.0

Nearly all of the breaking changes we are talking about are changes made by Ingest Node pipelines (as opposed to Go changes in Agent/Beats). The source data from the Agent is basically version agnostic w.r.t. these changes. This is good because it means users encounter the breaking schema change when they upgrade the integration rather than when they upgrade their stack or Agents. So think we are safe to release packages with these fields to 7.17 users (e.g. `kibana.version: ^7.17.0 || ^8.0.0`). This saves us from needing to create a branch to continue to support 7.17.

There was one instance in system/process where we are adding an ingest pipeline to rename process.ppid from 7.x Agents to process.parent.pid.

If we did forget to account for something on the Agent side that's producing the removed (log.original, process.ppid) then it can safely be ingested given that that the dynamic mappings match our removed mappings (keyword, long).


## About the ECS changes

Preparations began around 7.14 to remove these two ECS fields.

log.original should be safe to replace with event.original as Kibana logs UI has been updated in 7.14 to look for both event.original and log.original. https://github.com/elastic/ecs/blob/75d9daae17fdb3c3fef84cd5cbfd017ca156427a/rfcs/text/0017-remove-log-original.md#scope-of-impact

process.parent.pid has existed since ECS 1.3 (so a long time). Detection-rules have been exclusively using the new field since 7.13 (https://github.com/elastic/detection-rules/pull/1255). Beats was not updated until 8.0 to produce the new field. But AFAIK nothing in integrations uses the add_host_metadata processor so this should not be an issue for Agent/Fleet.  An assessment of the impact can be found at https://github.com/elastic/ecs/blob/main/rfcs/text/0022-remove-process-ppid.md#scope-of-impact. (Unrelated to Fleet, but to help Beat users transition from I've opened https://github.com/elastic/beats/issues/30070 which will give them overlap in 7.17 where both fields are produced.)

**Comment by ruflin** [comment]
> But AFAIK nothing in integrations uses the add_host_metadata processor so this should not be an issue for Agent/Fleet.

I thought under Elastic Agent you can't configure the processors but some of these are run by default / automatically (needs to be checked). Would this be an issue?

**Comment by r00tu53r** [comment]
Packages have been updated to ECS 8.0. Packages with breaking changes have undergone stack upgrade testing. No issues were found.
