### ISSUE TITLE
[System] Metricbeat fails because of missing system parts

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#90]
I suspect that dbus based datasets should be disabled by default. Otherwise, the docker image for Elastic-Agent fails. I suspect that it will fail also for ordinary environment where there is no dbus available.

```
2020-06-17T10:18:58.830Z	ERROR	[centralmgmt.fleet]	fleet/manager.go:261	2 errors: Error creating runner from config: 1 error: error connecting to dbus: error getting connection to system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory; Error creating runner from config: 1 error: error connecting to dbus: dial unix /run/systemd/private: connect: no such file or directory
```

I think we need to select a subset of datasets that is all-OS friendly, because we install system monitoring by default.

**Comment by mtojek** [comment]
Original issue: https://github.com/elastic/beats/issues/19241

**Comment by fearful-symmetry** [comment]
This should be fixed in 0.3.0 of the system package. What version are you testing with?

**Comment by mtojek** [comment]
I might have not updated the Package Registry locally, so that's false positive. Are other datasets safe to deploy on every platform? If so, you can resolve the issue.

**Comment by ph** [comment]
Is that still an issue?

**Comment by mtojek** [comment]
@fearful-symmetry ping

**Comment by tanvp112** [comment]
Hi,

In metricbeat.yml if service is enabled:
- module: system
  metricsets:
  ...
    - service        # systemd service information

metricbeat will fail to start: "error connecting to dbus: dial unix _/run/systemd/private: connect: no such file or directory_"

Looks like metricbeat cannot access the systemd path above. Whether system.hostfs is mapped or not this error persist.

Currently monitoring the service is disable in Metricbeat to avoid failure. Is this issue relate to this error?

**Comment by mtojek** [comment]
Not an issue anymore. Resolving.
